In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import math

In [12]:
A = np.array([[4, 0],
             [3, -5]])
df = pd.DataFrame(A, columns = ['f1', 'f2'])

In [21]:
#normilize dataset
df_norm = pd.DataFrame(np.array((df - df.mean()) / df.std(ddof=1)))
df_norm

0         1
0  0.707107  0.707107
1 -0.707107 -0.707107

In [14]:
x = StandardScaler().fit_transform(df)
x

array([[ 1.,  1.],
       [-1., -1.]])

In [15]:
df_norm.cov()

0    1
0  2.0  2.0
1  2.0  2.0

In [22]:
#calculate the covariance matrix for the while dataset
covariance = np.dot((df_norm - df_norm.mean()).T, (df_norm - df_norm.mean()))/(df_norm.shape[0]-1)
covariance

array([[1., 1.],
       [1., 1.]])

In [17]:
v1 = 1/2 * (np.trace(covariance) + math.sqrt((np.trace(covariance)**2) - 4 * np.linalg.det(covariance)))
v2 = 1/2 * (np.trace(covariance) - math.sqrt((np.trace(covariance)**2) - 4 * np.linalg.det(covariance)))

v1, v2

(4.0, 0.0)

In [18]:
#calculating eigenvalue and eigen vectors
value, vector = np.linalg.eig(covariance)
value, vector

(array([4.0000000e+00, 4.4408921e-16]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [19]:
W_T = vector.T
W_T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [20]:
Z = W_T.dot((df_norm - df_norm.mean()).T)
Z = pd.DataFrame(Z.T)
Z.head()

0             1
0  1.414214  2.220446e-16
1 -1.414214 -2.220446e-16