In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import math

In [40]:
A = np.array([[1, 2, 3, 4],
              [5, 5, 6, 7],
              [2, 4, 2, 3],
              [5, 3, 2, 1],
              [8, 1, 2, 2]])
df = pd.DataFrame(A, columns = ['f1', 'f2', 'f3', 'f4'])
df

f1  f2  f3  f4
0   1   2   3   4
1   5   5   6   7
2   2   4   2   3
3   5   3   2   1
4   8   1   2   2

In [41]:
#standartize datased
df_standartize = pd.DataFrame(np.array((df - df.mean()) / df.std(ddof=1)))
df_standartize

0         1         2         3
0 -1.153200 -0.632456  0.000000  0.260623
1  0.288300  1.264911  1.732051  1.563740
2 -0.792825  0.632456 -0.577350 -0.173749
3  0.288300  0.000000 -0.577350 -1.042493
4  1.369425 -1.264911 -0.577350 -0.608121

In [42]:
x = StandardScaler().fit_transform(df)    
x

array([[-1.28931674, -0.70710678,  0.        ,  0.29138576],
       [ 0.32232919,  1.41421356,  1.93649167,  1.74831455],
       [-0.88640526,  0.70710678, -0.64549722, -0.19425717],
       [ 0.32232919,  0.        , -0.64549722, -1.16554303],
       [ 1.53106363, -1.41421356, -0.64549722, -0.6799001 ]])

In [43]:
df_standartize.cov()

0         1             2         3
0  1.000000e+00 -0.284901 -1.954018e-17 -0.211325
1 -2.849014e-01  1.000000  6.390097e-01  0.618123
2 -1.954018e-17  0.639010  1.000000e+00  0.940443
3 -2.113248e-01  0.618123  9.404435e-01  1.000000

In [44]:
#calculate the covariance matrix for the while dataset
covariance = np.dot((df_standartize - df_standartize.mean()).T, (df_standartize - df_standartize.mean()))/(df_standartize.shape[0]-1)
covariance

array([[ 1.00000000e+00, -2.84901441e-01, -1.95401772e-17,
        -2.11324802e-01],
       [-2.84901441e-01,  1.00000000e+00,  6.39009650e-01,
         6.18122538e-01],
       [-1.95401772e-17,  6.39009650e-01,  1.00000000e+00,
         9.40443492e-01],
       [-2.11324802e-01,  6.18122538e-01,  9.40443492e-01,
         1.00000000e+00]])

In [45]:
def normalize_data(data):
    return (data - np.min(data)) / (np.max(data) - np.min(data))

In [46]:
normalize_data(df_standartize)

0     1     2         3
0  0.000000  0.25  0.25  0.500000
1  0.571429  1.00  1.00  1.000000
2  0.142857  0.75  0.00  0.333333
3  0.571429  0.50  0.00  0.000000
4  1.000000  0.00  0.00  0.166667

In [47]:
A / np.sqrt(np.sum(A**2))

array([[0.05679618, 0.11359237, 0.17038855, 0.22718473],
       [0.28398092, 0.28398092, 0.3407771 , 0.39757328],
       [0.11359237, 0.22718473, 0.11359237, 0.17038855],
       [0.28398092, 0.17038855, 0.11359237, 0.05679618],
       [0.45436947, 0.05679618, 0.11359237, 0.11359237]])

In [48]:
A/np.sqrt(np.sum(A**2))

array([[0.05679618, 0.11359237, 0.17038855, 0.22718473],
       [0.28398092, 0.28398092, 0.3407771 , 0.39757328],
       [0.11359237, 0.22718473, 0.11359237, 0.17038855],
       [0.28398092, 0.17038855, 0.11359237, 0.05679618],
       [0.45436947, 0.05679618, 0.11359237, 0.11359237]])

In [49]:
df/np.sqrt(np.sum(df.values**2))

f1        f2        f3        f4
0  0.056796  0.113592  0.170389  0.227185
1  0.283981  0.283981  0.340777  0.397573
2  0.113592  0.227185  0.113592  0.170389
3  0.283981  0.170389  0.113592  0.056796
4  0.454369  0.056796  0.113592  0.113592

In [50]:
A/np.linalg.norm(A)

array([[0.05679618, 0.11359237, 0.17038855, 0.22718473],
       [0.28398092, 0.28398092, 0.3407771 , 0.39757328],
       [0.11359237, 0.22718473, 0.11359237, 0.17038855],
       [0.28398092, 0.17038855, 0.11359237, 0.05679618],
       [0.45436947, 0.05679618, 0.11359237, 0.11359237]])

In [51]:
y_true = [0,0,0,0,0,0,0, 1,1,1,1,1,1,1,1, 2,2,2,2,2,2,2,2,2, 0, 1,1, 2,2,2, 0,0,0, 1,1, 2]
y_pred = [0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0, 1, 1,1, 1,1,1, 2,2,2, 2,2, 2]
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
print(confusion_matrix(y_pred, y_true))
print(precision_score(y_true, y_pred, average = None))
print(recall_score(y_true, y_pred, average = None))
print(f1_score(y_true, y_pred, average = None))

[[7 8 9]
 [1 2 3]
 [3 2 1]]
[0.29166667 0.33333333 0.16666667]
[0.63636364 0.16666667 0.07692308]
[0.4        0.22222222 0.10526316]


In [52]:
def confusion_matrix(actual, predicted):
    classes = np.unique(actual)
    M = np.zeros((len(classes), len(classes)))

    for i in range(len(classes)):
        for j in range(len(classes)):
           M[i, j] = np.sum((predicted == classes[i]) & (actual == classes[j]))

    return M
CM = confusion_matrix(y_true, y_pred)
print(CM)

[[7. 8. 9.]
 [1. 2. 3.]
 [3. 2. 1.]]


In [53]:
#recall
recall = []
for i in range(len(CM)):
    recall.append(CM[:,i][i]/np.sum(CM[:,i]))
recall

[0.6363636363636364, 0.16666666666666666, 0.07692307692307693]

In [54]:
#precision
precision = []
for i in range(len(CM)):
    precision.append(CM[:,i][i]/np.sum(CM[i,:]))
precision

[0.2916666666666667, 0.3333333333333333, 0.16666666666666666]

In [55]:
#f1 sco re
f1_score = []
for i in range(len(CM)):
    f1_score.append((2*precision[i]*recall[i])/(precision[i]+recall[i]))
f1_score

[0.4, 0.2222222222222222, 0.10526315789473684]